package:
  name: incqueryserver-jupyter
  version: "0.10.0"

source:
  path: ../../../../source/incqueryserver-jupyter
  
  
build:
  noarch: python
    
  
requirements:
  build:
    - python
    - setuptools
    - incqueryserver-api-python-client
    - ipywidgets
    - requests

  run:
    - python
    - incqueryserver-api-python-client
    - ipywidgets
    - requests

test:
  imports:
    - iqs_jupyter

about:
  home: https://github.com/IncQueryLabs/incquery-server-jupyter
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: IncQuery Server Client Extensions for Jupyter and Python
  